//
// SPDX-FileCopyrightText: Copyright 2025 Arm Limited and/or its affiliates <open-source-office@arm.com>
//
// SPDX-License-Identifier: Apache-2.0
//
#ifndef LLM_IMPL_HPP
#define LLM_IMPL_HPP

#include "Llm.hpp"
#include "LlmConfig.hpp"
#include "llm_inference_engine.h"
#include <string>
#include <mutex>
#include <condition_variable>

/**
 * @brief Structure to hold all members of llmEngine's callback utilities
 */
struct CallbackContext {

    /// Stores the asynchronous response string from the engine.
    std::string m_asyncResponse;

    /// Indicates whether the callback has completed.
    bool m_done = false;

    /// Synchronizes access to the callback state.
    std::mutex m_callbackMutex;

    /// Signals completion or state change for the callback.
    std::condition_variable m_callbackStatus;

    ///Models context filled indicator is moved here for efficient update
    int m_nCur;
};

/**
 * @brief Mediapipe Implementation of our LLM API
 */
class LLM::LLMImpl {

public:
    LLMImpl();
    ~LLMImpl();
    /**
     * Initializes the LLM engine and session with configuration settings.
     * @param config Configuration object containing model path and prefix.
     */
    void LlmInit(const LlmConfig& config);

    /**
     * Encodes a query and appends it to the current conversation context.
     * Adds the query chunk to the LLM engine session.
     * @param payload Input payload containing text and/or image path.
     */
    void Encode(EncodePayload& payload);

    /**
     * Method to extract tokens already generated by LLM engine from Mediapipe Framework.
     * @return response
     */
    std::string NextToken();

    /**
     * Function to retrieve the mediapipe encode timings.
     * @return The encoded tokens per second
     */
    float GetEncodeTimings();

    /**
     * Function to retrieve the mediapipe decode timings.
     * @return The decoded tokens per second
     */
    float GetDecodeTimings();

    /**
     * Function to reset the mediapipe encode/decode timings
     */
    void ResetTimings();

    /**
     * Function to print the system info
     * @return System info as a char pointer
     */
    const char* SystemInfo();

    /**
     * Function to clear KV Cache and hence all conversation history
     */
    void KVCacheClear();

    /**
     * Method to reset Conversation history and preserve Model's character prefix.
     * If model's prefix is not defined all conversation history would be cleared
     */
    void ResetContext();

    /**
     * Calculates and returns the percentage of context used in the chat.
     * @return Chat progress as a percentage of total context.
     */
    size_t GetChatProgress();

    /**
     * Frees the memory used by the LLM engine and session.
     * Cleans up allocated resources.
     */
    void FreeLlm();

    /**
     * ToDo Implement Decoding benchmark method
     * Benchmarks the model by encoding a repeated prompt sequence.
     * Computes and logs average and standard deviation of throughput.
     * @param prompts Number of prompts to process.
     * @param eval_prompts Number of evaluation prompts (currently unused).
     * @param n_max_sq Maximum sequence length (currently unused).
     * @param n_rep Number of repetitions for averaging results.
     * @return Benchmark result string.
     */
    std::string BenchModel(int& prompts, int& eval_prompts, int& n_max_sq, int& n_rep);

    /**
     * Method to get framework type
     * @return string framework type
     */
    std::string GetFrameworkType();

    /**
    * Method to Cancel generation of response tokens. Can be used to stop response once query commences
    */
    void StopGeneration();

    /**
     * @brief Build and return a query string from the given prompt and configuration.
     * @param prompt Input payload containing text, optional image, and conversation metadata.
     * @return The constructed query string to be passed to the model backend.
     */
    virtual std::string QueryBuilder(EncodePayload& prompt);

    /**
    * @brief List supported input modalities.
    * @return A vector containing {"text", "vision"}.
    */
    std::vector<std::string> SupportedInputModalities() const{  return {"text"};}



private:
    std::string m_frameworkType{"mediapipe"};
    void* m_llmEngine        = nullptr;
    char* m_errorMsg         = nullptr;
    void* m_llmEngineSession = nullptr;
    size_t m_nCtx            = 2048;
    size_t m_randomSeed      = 1234;
    std::string m_llmPrefix  = "";
    bool m_llmInitialized    = false;
    int m_errorCode          = -1;
    std::string m_conversationContext;
    LlmResponseContext m_llmResponseContext;
    CallbackContext m_callbackContext;
    std::string m_singleResponse;
    LlmConfig m_config;

    // Used as a general signal in our Llm module to terminate response
    std::string m_eos = "<|endoftext|>";

    /**
     * Function to tokenize the initial prompt
     * @param text - prompt text
     * @return number of tokens in the prompt.
     */
    int32_t GetInitialPromptLength(const char* text);

    /**
     * Loads the LLM engine from the provided model path and cache directory.
     * Initializes the engine with the given settings.
     * @param model_path Path to the LLM model file.
     * @param cache_dir Directory to use for caching intermediate artifacts.
     */
    void LoadEngine(const std::string& model_path, const std::string& cache_dir = "./");

    /**
     * Creates a session for the LLM engine using preset hyperparameters.
     * Initializes the session handle for inference.
     */
    void LoadSession();
};

#endif /* LLM_IMPL_HPP */
